In [1]:
import cv2
from neuralnet import NN, ConvLayer
from neuralnet import Pooling
from neuralnet import Flatten
from neuralnet import Dense
from neuralnet import load_model
import numpy as np
from neuralnet import Trainer
from neuralnet import Preprocess
from neuralnet import ImageDataset

In [2]:
newModel = load_model("base.json")

In [3]:
data_preprocess = Preprocess("../data", True)
data_kfold = data_preprocess.get_data_kfold(max_data_len=100)

In [4]:
def combine_datasets(datasets:list):
    combined = ImageDataset([])
    for dataset in datasets:
        combined.data += dataset.data
    return combined

evaluations = []
for i in range(len(data_kfold)):
    print("Fold", i+1)
    exclusion = [data for j, data in enumerate(data_kfold) if j != i]
    train_data = combine_datasets(exclusion)
    test_data = data_kfold[i]
    trainer = Trainer(
        newModel,
        1,
        0.1,
        train_data.get_images(),
        train_data.get_labels(),
        test_input=test_data.get_images(),
        test_label=test_data.get_labels(),
    )
    eval = trainer.fit(save=False)
    print()
    evaluations.append(eval)


Fold 1
Training model...
Epoch 1/1


c:\DATA\Smt9\mll\tubes-cnn\src\neuralnet\Activation.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-input))


Confusion Matrix:
[[90  0]
 [ 0  0]]
Accuracy: 100.00%
Average Precision: 50.00%
Average Recall: 50.00%
Average F1 Score: 50.00%
Training finished.

Fold 2
Training model...
Epoch 1/1
Confusion Matrix:
[[90  0]
 [ 0  0]]
Accuracy: 100.00%
Average Precision: 50.00%
Average Recall: 50.00%
Average F1 Score: 50.00%
Training finished.

Fold 3
Training model...
Epoch 1/1
Confusion Matrix:
[[90  0]
 [ 0  0]]
Accuracy: 100.00%
Average Precision: 50.00%
Average Recall: 50.00%
Average F1 Score: 50.00%
Training finished.

Fold 4
Training model...
Epoch 1/1
Confusion Matrix:
[[90  0]
 [ 0  0]]
Accuracy: 100.00%
Average Precision: 50.00%
Average Recall: 50.00%
Average F1 Score: 50.00%
Training finished.

Fold 5
Training model...
Epoch 1/1
Confusion Matrix:
[[90  0]
 [ 0  0]]
Accuracy: 100.00%
Average Precision: 50.00%
Average Recall: 50.00%
Average F1 Score: 50.00%
Training finished.

Fold 6
Training model...
Epoch 1/1
Confusion Matrix:
[[90  0]
 [ 0  0]]
Accuracy: 100.00%
Average Precision: 50.00%

In [8]:
acc = np.sum(np.array([eval.accuracy() for eval in evaluations])) / len(evaluations)
precision = np.sum(np.array([eval.precision() for eval in evaluations])) / len(evaluations)
recall = np.sum(np.array([eval.recall() for eval in evaluations])) / len(evaluations)
f1 = np.sum(np.array([eval.f1score() for eval in evaluations])) / len(evaluations)   

Accuracy: 100.00%
Accuracy: 100.00%
Accuracy: 100.00%
Accuracy: 100.00%
Accuracy: 100.00%
Accuracy: 100.00%
Accuracy: 100.00%
Accuracy: 100.00%
Accuracy: 100.00%
Accuracy: 100.00%
Average Precision: 50.00%
Average Precision: 50.00%
Average Precision: 50.00%
Average Precision: 50.00%
Average Precision: 50.00%
Average Precision: 50.00%
Average Precision: 50.00%
Average Precision: 50.00%
Average Precision: 50.00%
Average Precision: 50.00%
Average Recall: 50.00%
Average Recall: 50.00%
Average Recall: 50.00%
Average Recall: 50.00%
Average Recall: 50.00%
Average Recall: 50.00%
Average Recall: 50.00%
Average Recall: 50.00%
Average Recall: 50.00%
Average Recall: 50.00%
Average F1 Score: 50.00%
Average F1 Score: 50.00%
Average F1 Score: 50.00%
Average F1 Score: 50.00%
Average F1 Score: 50.00%
Average F1 Score: 50.00%
Average F1 Score: 50.00%
Average F1 Score: 50.00%
Average F1 Score: 50.00%
Average F1 Score: 50.00%


In [9]:
print("Summary")
print("Accuracy:", acc)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Summary
Accuracy: 1.0
Precision: 50.0
Recall: 50.0
F1 Score: 50.0
